import { useState, useEffect, useRef } from "react";
import { invoke } from "@tauri-apps/api/core";
import {
  useCreateWorkspace,
  useUpdateWorkspace,
  useDeleteWorkspace,
  useWorkspaces,
} from "@/hooks/useWorkspaces";
import { useCreatePanel, usePanels } from "@/hooks/usePanels";
import { useWorkspaceStore } from "@/store/useWorkspaceStore";
import { saveDynamicLayout } from "@/lib/db";
import { instantiateTemplate } from "@/lib/layoutTemplates";
import type { LayoutTemplate, Workspace } from "@/types";
import { ICON_OPTIONS, TEMPLATE_NAMES, LAYOUT_OPTIONS } from "@/lib/workspaceConstants";

// --- Etiqueta de sección ---

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <label style={{
      display: "block", marginBottom: 8,
      fontSize: 10, fontWeight: 700,
      color: "var(--text3)", letterSpacing: "0.08em",
      textTransform: "uppercase",
    }}>
      {children}
    </label>
  );
}

// --- Props ---

interface Props {
  open: boolean;
  workspace?: Workspace | null;
  startAtPanels?: boolean; // ignorado — ya no existe el paso de configuración de URLs
  onClose: () => void;
}

// --- WorkspaceDialog ---

export function WorkspaceDialog({ open, workspace, onClose }: Props) {
  const isEditing = !!workspace;

  const [nameEditing, setNameEditing] = useState(false);
  const [nameAutoGenerated, setNameAutoGenerated] = useState(true);
  const [name, setName] = useState("");
  const [icon, setIcon] = useState("Monitor");
  const [selectedTemplate, setSelectedTemplate] = useState<LayoutTemplate>("double");
  const [confirmDelete, setConfirmDelete] = useState(false);

  const nameInputRef = useRef<HTMLInputElement>(null);

  const createWorkspaceMutation = useCreateWorkspace();
  const updateWorkspaceMutation = useUpdateWorkspace();
  const deleteWorkspaceMutation = useDeleteWorkspace();
  const createPanel = useCreatePanel();

  const { data: workspaces = [] } = useWorkspaces();
  const { data: existingPanels = [] } = usePanels(isEditing ? workspace!.id : null);
  const { setActiveWorkspace, webviewMap, activeWorkspaceId, unregisterWebview } =
    useWorkspaceStore();

  useEffect(() => {
    if (!open) return;
    setNameEditing(false);
    setNameAutoGenerated(!isEditing);
    setName(isEditing ? (workspace!.name ?? "") : TEMPLATE_NAMES["double"]);
    setIcon(isEditing ? (workspace!.icon ?? "Monitor") : "Monitor");
    setSelectedTemplate("double");
    setConfirmDelete(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  useEffect(() => {
    if (nameEditing) {
      nameInputRef.current?.focus();
      nameInputRef.current?.select();
    }
  }, [nameEditing]);

  function handleTemplateChange(template: LayoutTemplate) {
    setSelectedTemplate(template);
    if (nameAutoGenerated) {
      setName(TEMPLATE_NAMES[template]);
    }
  }

  function confirmNameEdit() {
    setNameEditing(false);
    if (name.trim()) setNameAutoGenerated(false);
  }

  async function handleCreate() {
    if (!name.trim()) return;
    const newId = `ws-${Date.now()}`;
    await createWorkspaceMutation.mutateAsync({ id: newId, name: name.trim(), layout: "dynamic", icon });

    const dynLayout = instantiateTemplate(selectedTemplate);
    const allPanelIds = dynLayout.columns.flatMap((col) => col.panels.map((p) => p.panel_id));

    for (let i = 0; i < allPanelIds.length; i++) {
      await createPanel.mutateAsync({
        id: allPanelIds[i],
        workspace_id: newId,
        type: "WEB",
        url: undefined,
        widget_id: undefined,
        position: i,
      });
    }

    await saveDynamicLayout(newId, dynLayout);
    setActiveWorkspace(newId);
    handleClose();
  }

  async function handleSave() {
    if (!name.trim() || !workspace) return;
    await updateWorkspaceMutation.mutateAsync({
      id: workspace.id,
      name: name.trim(),
      icon,
      layout: "dynamic",
    });
    handleClose();
  }

  async function handleDelete() {
    if (!workspace) return;
    for (const panel of existingPanels) {
      if (webviewMap[panel.id]) {
        await invoke("destroy_panel_webview", { panelId: panel.id }).catch(console.error);
        unregisterWebview(panel.id);
      }
    }
    await deleteWorkspaceMutation.mutateAsync(workspace.id);
    if (activeWorkspaceId === workspace.id) {
      const remaining = workspaces.filter((ws) => ws.id !== workspace.id);
      if (remaining.length > 0) setActiveWorkspace(remaining[0].id);
    }
    handleClose();
  }

  function handleClose() {
    setNameEditing(false);
    setNameAutoGenerated(true);
    setName("");
    setIcon("Monitor");
    setSelectedTemplate("double");
    setConfirmDelete(false);
    onClose();
  }

  const isPending =
    createWorkspaceMutation.isPending ||
    updateWorkspaceMutation.isPending ||
    createPanel.isPending;

  if (!open) return null;

  return (
    <div
      style={{
        position: "fixed", inset: 0,
        background: "rgba(0,0,0,0.6)",
        backdropFilter: "blur(8px)",
        zIndex: 1000,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}
      onClick={(e) => e.target === e.currentTarget && handleClose()}
    >
      <div style={{
        width: 480,
        background: "var(--base-deep)",
        border: "1px solid var(--border2)",
        borderRadius: 16,
        overflow: "hidden",
        boxShadow: "0 32px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.04)",
      }}>
        {/* Header */}
        <div style={{
          padding: "20px 24px 16px",
          display: "flex", alignItems: "center", justifyContent: "space-between",
          borderBottom: "1px solid var(--border)",
        }}>
          <span style={{ fontSize: 12, color: "var(--text3)" }}>
            {isEditing ? "Editar workspace" : "Nuevo workspace"}
          </span>
          <button
            onClick={handleClose}
            style={{
              width: 24, height: 24,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRadius: 6,
              background: "transparent", border: "none",
              color: "var(--text3)", fontSize: 14, cursor: "pointer",
              transition: "background 0.15s, color 0.15s",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = "rgba(255,255,255,0.08)";
              e.currentTarget.style.color = "var(--text)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = "transparent";
              e.currentTarget.style.color = "var(--text3)";
            }}
          >
            ×
          </button>
        </div>

        {/* Contenido */}
        <div style={{ padding: "16px 24px 24px", display: "flex", flexDirection: "column", gap: 20 }}>

          {/* Selector de icono */}
          <div>
            <SectionLabel>Icono</SectionLabel>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 6 }}>
              {ICON_OPTIONS.map(({ name: iconName, Icon }) => {
                const isSelected = icon === iconName;
                return (
                  <button
                    key={iconName}
                    onClick={() => setIcon(iconName)}
                    title={iconName}
                    style={{
                      height: 40,
                      display: "flex", alignItems: "center", justifyContent: "center",
                      borderRadius: 8,
                      background: isSelected ? "rgba(124,106,247,0.15)" : "rgba(255,255,255,0.04)",
                      border: isSelected
                        ? "1px solid rgba(124,106,247,0.5)"
                        : "1px solid rgba(255,255,255,0.08)",
                      cursor: "pointer",
                      color: isSelected ? "var(--accent)" : "var(--text3)",
                      transition: "all 0.15s",
                    }}
                    onMouseEnter={(e) => {
                      if (!isSelected) {
                        e.currentTarget.style.background = "rgba(124,106,247,0.1)";
                        e.currentTarget.style.color = "var(--accent2)";
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!isSelected) {
                        e.currentTarget.style.background = "rgba(255,255,255,0.04)";
                        e.currentTarget.style.color = "var(--text3)";
                      }
                    }}
                  >
                    <Icon size={16} />
                  </button>
                );
              })}
            </div>
          </div>

          {/* Selector de template — solo al crear */}
          {!isEditing && (
            <div>
              <SectionLabel>Layout</SectionLabel>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6 }}>
                {LAYOUT_OPTIONS.map((opt) => (
                  <button
                    key={opt.value}
                    onClick={() => handleTemplateChange(opt.value)}
                    style={{
                      display: "flex", flexDirection: "column",
                      alignItems: "center", gap: 6,
                      padding: "10px 6px",
                      borderRadius: 10,
                      background: selectedTemplate === opt.value
                        ? "rgba(124,106,247,0.1)"
                        : "rgba(255,255,255,0.03)",
                      border: selectedTemplate === opt.value
                        ? "1px solid rgba(124,106,247,0.4)"
                        : "1px solid var(--border)",
                      cursor: "pointer",
                      transition: "all 0.15s",
                      transform: selectedTemplate === opt.value ? "translateY(-1px)" : "none",
                      boxShadow: selectedTemplate === opt.value
                        ? "0 4px 12px rgba(124,106,247,0.2)"
                        : "none",
                    }}
                  >
                    {opt.preview(selectedTemplate === opt.value)}
                    <span style={{
                      fontSize: 10, fontWeight: 600,
                      color: selectedTemplate === opt.value ? "var(--accent)" : "var(--text2)",
                    }}>
                      {opt.label}
                    </span>
                    <span style={{ fontSize: 9, color: "var(--text3)", textAlign: "center" }}>
                      {opt.description}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Nombre */}
          <div>
            <SectionLabel>Nombre</SectionLabel>
            {nameEditing ? (
              <input
                ref={nameInputRef}
                value={name}
                onChange={(e) => setName(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && confirmNameEdit()}
                onBlur={confirmNameEdit}
                placeholder="Mi workspace"
                style={{
                  width: "100%",
                  background: "var(--surface)",
                  border: "1px solid var(--accent)",
                  borderRadius: 8,
                  padding: "7px 12px",
                  fontSize: 13,
                  color: "var(--text)",
                  outline: "none",
                  boxSizing: "border-box",
                  boxShadow: "0 0 0 3px rgba(124,106,247,0.12)",
                }}
              />
            ) : (
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{
                  display: "inline-flex", alignItems: "center",
                  padding: "4px 12px",
                  background: "rgba(124,106,247,0.08)",
                  border: "1px solid rgba(124,106,247,0.2)",
                  borderRadius: 20,
                  fontSize: 13, fontWeight: 500,
                  color: "var(--text)",
                }}>
                  {name || "Sin nombre"}
                </span>
                <button
                  onClick={() => setNameEditing(true)}
                  style={{
                    fontSize: 11, color: "var(--text3)",
                    background: "none", border: "none",
                    cursor: "pointer", padding: 0,
                    transition: "color 0.15s",
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.color = "var(--accent2)")}
                  onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text3)")}
                >
                  editar
                </button>
              </div>
            )}
          </div>

          {/* Zona de peligro — solo en modo edición */}
          {isEditing && (
            <div style={{ paddingTop: 4, borderTop: "1px solid var(--border)" }}>
              {!confirmDelete ? (
                <button
                  onClick={() => setConfirmDelete(true)}
                  onMouseEnter={(e) => (e.currentTarget.style.color = "#f87171")}
                  onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text3)")}
                  style={{
                    fontSize: 11, color: "var(--text3)",
                    background: "none", border: "none",
                    cursor: "pointer", padding: 0,
                    transition: "color 0.15s",
                  }}
                >
                  Eliminar workspace…
                </button>
              ) : (
                <div style={{
                  padding: "12px 14px", borderRadius: 8,
                  background: "rgba(239,68,68,0.08)",
                  border: "1px solid rgba(239,68,68,0.25)",
                }}>
                  <p style={{ fontSize: 12, color: "#fca5a5", margin: "0 0 10px 0" }}>
                    ¿Eliminar «{workspace?.name}»? Esta acción no se puede deshacer.
                  </p>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button
                      onClick={() => setConfirmDelete(false)}
                      style={{
                        flex: 1, fontSize: 11, padding: "5px 0",
                        background: "rgba(255,255,255,0.05)",
                        border: "1px solid var(--border2)",
                        borderRadius: 6, cursor: "pointer",
                        color: "var(--text3)",
                      }}
                    >
                      Cancelar
                    </button>
                    <button
                      onClick={handleDelete}
                      disabled={deleteWorkspaceMutation.isPending}
                      style={{
                        flex: 1, fontSize: 11, padding: "5px 0",
                        background: "#ef4444", color: "#fff",
                        border: "none", borderRadius: 6,
                        cursor: deleteWorkspaceMutation.isPending ? "default" : "pointer",
                        fontWeight: 600,
                        opacity: deleteWorkspaceMutation.isPending ? 0.6 : 1,
                      }}
                    >
                      Eliminar
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Botones */}
          <div style={{ display: "flex", gap: 8, marginTop: 4 }}>
            <div style={{ flex: 1 }} />
            <button
              onClick={handleClose}
              style={{
                padding: "7px 16px", borderRadius: 8,
                background: "transparent",
                border: "1px solid var(--border2)",
                color: "var(--text3)", fontSize: 12, cursor: "pointer",
              }}
            >
              Cancelar
            </button>
            <button
              onClick={isEditing ? handleSave : handleCreate}
              disabled={!name.trim() || isPending}
              style={{
                padding: "7px 16px", borderRadius: 8,
                background: !name.trim() ? "var(--border2)" : "var(--accent)",
                border: "none",
                color: "#fff", fontSize: 12, fontWeight: 600,
                cursor: (!name.trim() || isPending) ? "default" : "pointer",
                transition: "all 0.15s",
                opacity: isPending ? 0.6 : 1,
              }}
            >
              {isEditing ? "Guardar" : "Crear"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
